import type { SupportResource } from "@kindminds/types";

export const DEFAULT_VERIFIED_RESOURCES: SupportResource[] = [
  {
    id: "res-irct-global",
    name: "International Rehabilitation Council for Torture Victims (IRCT)",
    description: "Global umbrella organization supporting over 160 independent torture rehabilitation centers across 76 countries.",
    countryCode: "GLOBAL",
    region: "Worldwide",
    website: "https://irct.org",
    specialty: "torture_rehabilitation",
    languages: ["English", "French", "Spanish", "Arabic"],
    freeAndConfidential: true,
  },
  {
    id: "res-cvt-us-intl",
    name: "Center for Victims of Torture (CVT)",
    description: "Specialized clinical and psychosocial care, trauma rehabilitation, and healing for survivors of politically motivated torture and atrocities.",
    countryCode: "US",
    region: "Global & United States",
    hotline: "+1-612-436-4800",
    website: "https://www.cvt.org",
    specialty: "torture_rehabilitation",
    languages: ["English", "Arabic", "Oromo", "Somali", "Spanish", "Tigrinya"],
    freeAndConfidential: true,
  },
  {
    id: "res-fft-uk",
    name: "Freedom from Torture",
    description: "UK-based medical foundation offering psychological therapies, pain clinics, and legal forensic documentation for torture survivors.",
    countryCode: "UK",
    region: "United Kingdom",
    hotline: "+44-20-7697-7777",
    website: "https://www.freedomfromtorture.org",
    specialty: "torture_rehabilitation",
    languages: ["English", "Farsi", "Arabic", "Kurdish", "French"],
    freeAndConfidential: true,
  },
  {
    id: "res-msf-trauma",
    name: "Doctors Without Borders (MSF) Mental Health Teams",
    description: "Emergency psychosocial support for populations affected by armed conflicts, atrocities, epidemics, and disasters.",
    countryCode: "GLOBAL",
    region: "Active Conflict Zones & Refugee Corridors",
    website: "https://www.msf.org",
    specialty: "war_atrocities",
    languages: ["English", "Arabic", "French", "Ukrainian", "Russian", "Spanish"],
    freeAndConfidential: true,
  },
  {
    id: "res-befrienders",
    name: "Befrienders Worldwide",
    description: "Confidential emotional support and suicide crisis assistance worldwide.",
    countryCode: "GLOBAL",
    region: "Global Network",
    website: "https://www.befrienders.org",
    specialty: "crisis_helplines",
    languages: ["Multiple"],
    freeAndConfidential: true,
  },
  {
    id: "res-988-us",
    name: "988 Suicide & Crisis Lifeline",
    description: "24/7 free and confidential crisis support in the United States and Canada.",
    countryCode: "US",
    region: "United States",
    hotline: "988",
    smsText: "988",
    website: "https://988lifeline.org",
    specialty: "crisis_helplines",
    languages: ["English", "Spanish"],
    freeAndConfidential: true,
  },
  {
    id: "res-unhcr-protection",
    name: "UNHCR Refugee & Asylum Protection Directory",
    description: "Emergency legal protection and psycho-social referral mechanisms for forcibly displaced survivors.",
    countryCode: "GLOBAL",
    region: "Worldwide",
    website: "https://help.unhcr.org",
    specialty: "refugee_legal_aid",
    languages: ["Arabic", "English", "French", "Ukrainian", "Spanish"],
    freeAndConfidential: true,
  },
  {
    id: "res-voices-children-ua",
    name: "Voices of Children Foundation (Kyiv)",
    description: "Psychological and psychosocial support for war-traumatized children, families, and atrocity survivors in Ukraine.",
    countryCode: "UA",
    region: "Ukraine & Eastern Europe",
    hotline: "+380-800-210-106",
    website: "https://voices.org.ua",
    specialty: "war_atrocities",
    languages: ["Ukrainian", "English", "Russian"],
    freeAndConfidential: true,
  },
];
