/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssessmentsRouteImport } from './routes/assessments'
import { Route as ExportRouteImport } from './routes/export'
import { Route as GroundingRouteImport } from './routes/grounding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SafetyPlanRouteImport } from './routes/safety-plan'
import { Route as TriageRouteImport } from './routes/triage'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsRoute = AssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const GroundingRoute = GroundingRouteImport.update({
  id: '/grounding',
  path: '/grounding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyPlanRoute = SafetyPlanRouteImport.update({
  id: '/safety-plan',
  path: '/safety-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const TriageRoute = TriageRouteImport.update({
  id: '/triage',
  path: '/triage',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessments': typeof AssessmentsRoute
  '/export': typeof ExportRoute
  '/grounding': typeof GroundingRoute
  '/login': typeof LoginRoute
  '/safety-plan': typeof SafetyPlanRoute
  '/triage': typeof TriageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessments': typeof AssessmentsRoute
  '/export': typeof ExportRoute
  '/grounding': typeof GroundingRoute
  '/login': typeof LoginRoute
  '/safety-plan': typeof SafetyPlanRoute
  '/triage': typeof TriageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assessments': typeof AssessmentsRoute
  '/export': typeof ExportRoute
  '/grounding': typeof GroundingRoute
  '/login': typeof LoginRoute
  '/safety-plan': typeof SafetyPlanRoute
  '/triage': typeof TriageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessments'
    | '/export'
    | '/grounding'
    | '/login'
    | '/safety-plan'
    | '/triage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessments'
    | '/export'
    | '/grounding'
    | '/login'
    | '/safety-plan'
    | '/triage'
  id:
    | '__root__'
    | '/'
    | '/assessments'
    | '/export'
    | '/grounding'
    | '/login'
    | '/safety-plan'
    | '/triage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessmentsRoute: typeof AssessmentsRoute
  ExportRoute: typeof ExportRoute
  GroundingRoute: typeof GroundingRoute
  LoginRoute: typeof LoginRoute
  SafetyPlanRoute: typeof SafetyPlanRoute
  TriageRoute: typeof TriageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments': {
      id: '/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grounding': {
      id: '/grounding'
      path: '/grounding'
      fullPath: '/grounding'
      preLoaderRoute: typeof GroundingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety-plan': {
      id: '/safety-plan'
      path: '/safety-plan'
      fullPath: '/safety-plan'
      preLoaderRoute: typeof SafetyPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/triage': {
      id: '/triage'
      path: '/triage'
      fullPath: '/triage'
      preLoaderRoute: typeof TriageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessmentsRoute: AssessmentsRoute,
  ExportRoute: ExportRoute,
  GroundingRoute: GroundingRoute,
  LoginRoute: LoginRoute,
  SafetyPlanRoute: SafetyPlanRoute,
  TriageRoute: TriageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
