// @ts-ignore - Generated by TanStack Start / Vite build
import server from "../dist/server/server.js";
import { getAuth } from "./auth";

export default {
  async fetch(request: Request, env: any, ctx: any): Promise<Response> {
    const url = new URL(request.url);

    // 1. BetterAuth API Handler
    if (url.pathname.startsWith("/api/auth")) {
      try {
        const auth = getAuth(env.DB, {
          secret: env.BETTER_AUTH_SECRET,
          baseURL: env.BETTER_AUTH_URL,
        });
        return await auth.handler(request);
      } catch (err: any) {
        return new Response(
          JSON.stringify({
            error: err.message,
            stack: err.stack,
          }),
          {
            status: 500,
            headers: { "Content-Type": "application/json" },
          }
        );
      }
    }

    // 2. TanStack Start SSR & Server Functions Handler
    return server.fetch(request, env, ctx);
  },
};
